function detections = generateTestDetections()
%GENERATETESTDETECTIONS Generates synthetic camera, LiDAR and radar
% detections for Phase-1 sensor association testing.
%
% Output:
%   detections - Structure containing test detections from:
%                8 cameras, 1 LiDAR and 5 radars

    % Common timestamp
    timestamp = 1.000;

    % ---------------------------------------------------------
    % CAMERA DETECTIONS
    % ---------------------------------------------------------

    detections.camera(1) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_front", ...
        "car", ...
        [20.30 2.10], ...
        [5.00 0.20], ...
        0.92, ...
        "vehicle");

    detections.camera(2) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_front_left", ...
        "car", ...
        [20.40 2.20], ...
        [5.00 0.20], ...
        0.89, ...
        "vehicle");

    detections.camera(3) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_front_right", ...
        "car", ...
        [20.20 2.00], ...
        [5.10 0.20], ...
        0.91, ...
        "vehicle");

    detections.camera(4) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_rear", ...
        "car", ...
        [20.60 2.10], ...
        [4.90 0.20], ...
        0.87, ...
        "vehicle");

    detections.camera(5) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_rear_left", ...
        "car", ...
        [20.50 2.20], ...
        [4.90 0.20], ...
        0.86, ...
        "vehicle");

    detections.camera(6) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_rear_right", ...
        "car", ...
        [20.70 2.00], ...
        [4.80 0.10], ...
        0.88, ...
        "vehicle");

    detections.camera(7) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_left", ...
        "car", ...
        [20.40 2.00], ...
        [5.00 0.20], ...
        0.84, ...
        "vehicle");

    detections.camera(8) = createDetection( ...
        timestamp, ...
        "camera", ...
        "camera_right", ...
        "car", ...
        [20.30 2.20], ...
        [5.00 0.20], ...
        0.85, ...
        "vehicle");


    % ---------------------------------------------------------
    % LiDAR DETECTION
    % ---------------------------------------------------------

    detections.lidar = createDetection( ...
        timestamp, ...
        "lidar", ...
        "lidar_main", ...
        "car", ...
        [20.50 2.05], ...
        [4.90 0.15], ...
        0.95, ...
        "vehicle");


    % ---------------------------------------------------------
    % RADAR DETECTIONS
    % ---------------------------------------------------------

    detections.radar(1) = createDetection( ...
        timestamp, ...
        "radar", ...
        "radar_front", ...
        "car", ...
        [20.80 2.00], ...
        [4.80 0.10], ...
        0.88, ...
        "vehicle");

    detections.radar(2) = createDetection( ...
        timestamp, ...
        "radar", ...
        "radar_front_left", ...
        "car", ...
        [20.70 2.10], ...
        [4.90 0.10], ...
        0.86, ...
        "vehicle");

    detections.radar(3) = createDetection( ...
        timestamp, ...
        "radar", ...
        "radar_front_right", ...
        "car", ...
        [20.90 1.90], ...
        [4.70 0.10], ...
        0.87, ...
        "vehicle");

    detections.radar(4) = createDetection( ...
        timestamp, ...
        "radar", ...
        "radar_rear_left", ...
        "car", ...
        [20.60 2.20], ...
        [4.80 0.20], ...
        0.82, ...
        "vehicle");

    detections.radar(5) = createDetection( ...
        timestamp, ...
        "radar", ...
        "radar_rear_right", ...
        "car", ...
        [20.90 2.10], ...
        [4.70 0.10], ...
        0.83, ...
        "vehicle");

end