function scenario = generateDynamicScenario()
%GENERATEDYNAMICSCENARIO
% Generates time-varying multi-object sensor data.
%
% Objects:
%   1. Car
%   2. Motorcycle
%   3. Pedestrian
%
% Time:
%   10 simulation steps
%
% Sensors:
%   Camera
%   LiDAR
%   Radar
%
% The generated data contains:
%   - Ground-truth object positions
%   - Camera measurements
%   - LiDAR measurements
%   - Radar measurements

    % ---------------------------------------------------------
    % Simulation settings
    % ---------------------------------------------------------

    numSteps = 10;
    dt = 0.1;

    scenario.time = zeros(1, numSteps);

    % ---------------------------------------------------------
    % Ground-truth initial states
    %
    % position = [x y] in metres
    % velocity = [vx vy] in m/s
    % ---------------------------------------------------------

    % Car
    carPosition = [20.0 2.0];
    carVelocity = [5.0 0.2];

    % Motorcycle
    motorcyclePosition = [12.0 -3.0];
    motorcycleVelocity = [6.0 0.8];

    % Pedestrian
    pedestrianPosition = [8.0 4.0];
    pedestrianVelocity = [0.2 -0.5];

    % ---------------------------------------------------------
    % Generate data for every time step
    % ---------------------------------------------------------

    for k = 1:numSteps

        timestamp = (k - 1) * dt;
        scenario.time(k) = timestamp;

        % =====================================================
        % GROUND TRUTH
        % =====================================================

        scenario.groundTruth(k).car.position = carPosition;
        scenario.groundTruth(k).car.velocity = carVelocity;

        scenario.groundTruth(k).motorcycle.position = ...
            motorcyclePosition;

        scenario.groundTruth(k).motorcycle.velocity = ...
            motorcycleVelocity;

        scenario.groundTruth(k).pedestrian.position = ...
            pedestrianPosition;

        scenario.groundTruth(k).pedestrian.velocity = ...
            pedestrianVelocity;


        % =====================================================
        % CAMERA MEASUREMENTS
        % =====================================================

        % Car
        scenario.camera(k,1) = createDetection( ...
            timestamp, ...
            "camera", ...
            "camera_front", ...
            "car", ...
            carPosition + [0.10 -0.05], ...
            carVelocity + [0.05 0.02], ...
            0.92, ...
            "vehicle");

        % Motorcycle
        scenario.camera(k,2) = createDetection( ...
            timestamp, ...
            "camera", ...
            "camera_front_right", ...
            "motorcycle", ...
            motorcyclePosition + [-0.08 0.06], ...
            motorcycleVelocity + [0.03 -0.02], ...
            0.89, ...
            "vehicle");

        % Pedestrian
        scenario.camera(k,3) = createDetection( ...
            timestamp, ...
            "camera", ...
            "camera_front_left", ...
            "pedestrian", ...
            pedestrianPosition + [0.05 0.08], ...
            pedestrianVelocity + [0.02 0.01], ...
            0.94, ...
            "vehicle");


        % =====================================================
        % LiDAR MEASUREMENTS
        % =====================================================

        % Car
        scenario.lidar(k,1) = createDetection( ...
            timestamp, ...
            "lidar", ...
            "lidar_main", ...
            "car", ...
            carPosition + [-0.05 0.03], ...
            carVelocity + [-0.02 0.01], ...
            0.96, ...
            "vehicle");

        % Motorcycle
        scenario.lidar(k,2) = createDetection( ...
            timestamp, ...
            "lidar", ...
            "lidar_main", ...
            "motorcycle", ...
            motorcyclePosition + [0.04 -0.03], ...
            motorcycleVelocity + [-0.02 0.03], ...
            0.93, ...
            "vehicle");

        % Pedestrian
        scenario.lidar(k,3) = createDetection( ...
            timestamp, ...
            "lidar", ...
            "lidar_main", ...
            "pedestrian", ...
            pedestrianPosition + [-0.03 0.04], ...
            pedestrianVelocity + [0.01 -0.01], ...
            0.95, ...
            "vehicle");


        % =====================================================
        % RADAR MEASUREMENTS
        % =====================================================

        % Car
        scenario.radar(k,1) = createDetection( ...
            timestamp, ...
            "radar", ...
            "radar_front", ...
            "car", ...
            carPosition + [0.20 -0.02], ...
            carVelocity + [-0.10 0.00], ...
            0.88, ...
            "vehicle");

        % Motorcycle
        scenario.radar(k,2) = createDetection( ...
            timestamp, ...
            "radar", ...
            "radar_front_right", ...
            "motorcycle", ...
            motorcyclePosition + [0.15 0.05], ...
            motorcycleVelocity + [-0.08 0.02], ...
            0.86, ...
            "vehicle");

        % Pedestrian
        scenario.radar(k,3) = createDetection( ...
            timestamp, ...
            "radar", ...
            "radar_front_left", ...
            "pedestrian", ...
            pedestrianPosition + [0.10 -0.05], ...
            pedestrianVelocity + [0.00 0.02], ...
            0.80, ...
            "vehicle");


        % =====================================================
        % UPDATE GROUND-TRUTH STATES
        % =====================================================

        carPosition = carPosition + carVelocity * dt;

        motorcyclePosition = ...
            motorcyclePosition + motorcycleVelocity * dt;

        pedestrianPosition = ...
            pedestrianPosition + pedestrianVelocity * dt;

    end

end