function detections = generateMultiObjectDetections()
%GENERATEMULTIOBJECTDETECTIONS
% Generates synthetic multi-object camera and LiDAR detections
% for Phase-1 association testing.
%
% Objects:
%   1. Car
%   2. Motorcycle
%   3. Pedestrian
%
% Sensors:
%   8 Cameras
%   1 LiDAR
%
% All measurements are expressed in the vehicle frame.

    % Common timestamp
    timestamp = 1.000;

    % =========================================================
    % CAMERA DETECTIONS
    % =========================================================

    % -------- CAR --------

    detections.camera(1) = createDetection( ...
        timestamp, "camera", "camera_front", ...
        "car", [20.30 2.10], [5.00 0.20], ...
        0.92, "vehicle");

    detections.camera(2) = createDetection( ...
        timestamp, "camera", "camera_front_left", ...
        "car", [20.40 2.20], [5.00 0.20], ...
        0.89, "vehicle");

    detections.camera(3) = createDetection( ...
        timestamp, "camera", "camera_front_right", ...
        "car", [20.20 2.00], [5.10 0.20], ...
        0.91, "vehicle");


    % -------- MOTORCYCLE --------

    detections.camera(4) = createDetection( ...
        timestamp, "camera", "camera_front", ...
        "motorcycle", [12.20 -3.10], [7.00 0.50], ...
        0.90, "vehicle");

    detections.camera(5) = createDetection( ...
        timestamp, "camera", "camera_front_right", ...
        "motorcycle", [12.35 -3.00], [7.10 0.50], ...
        0.87, "vehicle");


    % -------- PEDESTRIAN --------

    detections.camera(6) = createDetection( ...
        timestamp, "camera", "camera_front_left", ...
        "pedestrian", [8.10 4.20], [0.50 0.00], ...
        0.94, "vehicle");

    detections.camera(7) = createDetection( ...
        timestamp, "camera", "camera_left", ...
        "pedestrian", [8.00 4.30], [0.50 0.00], ...
        0.91, "vehicle");


    % -------- SECOND CAR --------

    detections.camera(8) = createDetection( ...
        timestamp, "camera", "camera_right", ...
        "car", [30.20 -2.00], [4.00 -0.10], ...
        0.88, "vehicle");


    % =========================================================
    % LiDAR DETECTIONS
    % =========================================================

    % Car
    detections.lidar(1) = createDetection( ...
        timestamp, "lidar", "lidar_main", ...
        "car", [20.45 2.05], [4.90 0.15], ...
        0.96, "vehicle");

    % Motorcycle
    detections.lidar(2) = createDetection( ...
        timestamp, "lidar", "lidar_main", ...
        "motorcycle", [12.35 -3.05], [7.05 0.45], ...
        0.93, "vehicle");

    % Pedestrian
    detections.lidar(3) = createDetection( ...
        timestamp, "lidar", "lidar_main", ...
        "pedestrian", [8.05 4.25], [0.45 0.00], ...
        0.95, "vehicle");

    % Second car
    detections.lidar(4) = createDetection( ...
        timestamp, "lidar", "lidar_main", ...
        "car", [30.30 -2.05], [4.10 -0.10], ...
        0.91, "vehicle");

end