clc;
clear;

fprintf("\n");
fprintf("====================================================\n");
fprintf("UNCERTAINTY-AWARE TRACKING TEST\n");
fprintf("====================================================\n");


% -----------------------------------------------------
% Create initial fused detection
% -----------------------------------------------------

camera = createDetection( ...
    0.0, ...
    "camera", ...
    "camera_front", ...
    "car", ...
    [20.0 2.0], ...
    [5.0 0.2], ...
    0.80, ...
    "vehicle");


lidar = createDetection( ...
    0.0, ...
    "lidar", ...
    "lidar_main", ...
    "car", ...
    [20.1 2.0], ...
    [5.0 0.2], ...
    0.95, ...
    "vehicle");


radar = createDetection( ...
    0.0, ...
    "radar", ...
    "radar_front", ...
    "car", ...
    [20.2 2.0], ...
    [5.0 0.2], ...
    0.90, ...
    "vehicle");


detections = [camera lidar radar];


% -----------------------------------------------------
% Fuse sensors
% -----------------------------------------------------

fusedDetection = ...
    fuseDetections(detections);


% -----------------------------------------------------
% First tracker update
% -----------------------------------------------------

tracks = ...
    updateTracks([], fusedDetection);


fprintf("\nINITIAL TRACK\n");
fprintf("--------------------------------------------\n");

fprintf("Track ID          : %d\n", ...
    tracks(1).id);

fprintf("Class             : %s\n", ...
    tracks(1).class);

fprintf("Position          : [%.3f %.3f] m\n", ...
    tracks(1).position(1), ...
    tracks(1).position(2));

fprintf("Velocity          : [%.3f %.3f] m/s\n", ...
    tracks(1).velocity(1), ...
    tracks(1).velocity(2));

fprintf("Confidence        : %.3f\n", ...
    tracks(1).confidence);

fprintf("Position variance : %.6f m^2\n", ...
    tracks(1).positionVariance);

fprintf("Position std      : %.6f m\n", ...
    tracks(1).positionStd);


% -----------------------------------------------------
% Second measurement
% -----------------------------------------------------

camera = createDetection( ...
    0.1, ...
    "camera", ...
    "camera_front", ...
    "car", ...
    [20.5 2.02], ...
    [5.0 0.2], ...
    0.80, ...
    "vehicle");


lidar = createDetection( ...
    0.1, ...
    "lidar", ...
    "lidar_main", ...
    "car", ...
    [20.6 2.00], ...
    [5.0 0.2], ...
    0.95, ...
    "vehicle");


radar = createDetection( ...
    0.1, ...
    "radar", ...
    "radar_front", ...
    "car", ...
    [20.55 2.04], ...
    [5.0 0.2], ...
    0.90, ...
    "vehicle");


detections = [camera lidar radar];


% -----------------------------------------------------
% Fuse second measurement
% -----------------------------------------------------

fusedDetection = ...
    fuseDetections(detections);


% -----------------------------------------------------
% Update tracker
% -----------------------------------------------------

tracks = ...
    updateTracks(tracks, fusedDetection);


fprintf("\nSECOND UPDATE\n");
fprintf("--------------------------------------------\n");

fprintf("Track ID          : %d\n", ...
    tracks(1).id);

fprintf("Position          : [%.3f %.3f] m\n", ...
    tracks(1).position(1), ...
    tracks(1).position(2));

fprintf("Velocity          : [%.3f %.3f] m/s\n", ...
    tracks(1).velocity(1), ...
    tracks(1).velocity(2));

fprintf("Confidence        : %.3f\n", ...
    tracks(1).confidence);

fprintf("Position variance : %.6f m^2\n", ...
    tracks(1).positionVariance);

fprintf("Position std      : %.6f m\n", ...
    tracks(1).positionStd);

fprintf("Association dist  : %.6f\n", ...
    tracks(1).associationDistance);


% -----------------------------------------------------
% Final validation
% -----------------------------------------------------

fprintf("\n====================================================\n");
fprintf("VALIDATION\n");
fprintf("====================================================\n");


if tracks(1).hits >= 2
    fprintf("PASS: Track maintained same object.\n");
else
    fprintf("FAIL: Track was not updated.\n");
end


if tracks(1).positionStd < 1.0
    fprintf("PASS: Position uncertainty is reasonable.\n");
else
    fprintf("FAIL: Position uncertainty is too high.\n");
end


if tracks(1).associationDistance <= sqrt(9.21)
    fprintf("PASS: Mahalanobis association accepted.\n");
else
    fprintf("FAIL: Association distance too large.\n");
end


fprintf("\n====================================================\n");
fprintf("TEST COMPLETE\n");
fprintf("====================================================\n");