% BUILD_SIMULINK_MODEL - Programmatically constructs and saves the vehicle_control_system.slx model
% SIH Problem Statement 26037: Meghana - Vehicle Dynamics & Control

function model_name = build_simulink_model()
    model_name = 'vehicle_control_system';
    
    cur_dir = fileparts(mfilename('fullpath'));
    project_root = fileparts(cur_dir);
    slx_file = fullfile(cur_dir, [model_name, '.slx']);

    fprintf('Creating Simulink model: %s ...\n', slx_file);

    % Close model if already open
    if bdIsLoaded(model_name)
        close_system(model_name, 0);
    end

    % Create new system
    new_system(model_name);
    open_system(model_name);

    % Configure solver parameters for fixed-step autonomous vehicle simulation
    set_param(model_name, 'SolverType', 'Fixed-step');
    set_param(model_name, 'Solver', 'FixedStepAuto');
    set_param(model_name, 'FixedStep', '0.05');
    set_param(model_name, 'StopTime', '12.0');

    % Set up model workspace / preload callback
    set_param(model_name, 'PreLoadFcn', sprintf([...
        'addpath(genpath(''%s''));\n' ...
        'vp = vehicle_params();\n' ...
        'cp = controller_params();\n' ...
        'scenarios = generate_scenarios();\n' ...
        'trajectory = scenarios.pothole_dodge;\n' ...
        'control_mode = ''mpc'';\n'], project_root));

    % Add Constant Block: Trajectory Selector
    add_block('simulink/Sources/Constant', [model_name, '/ControlMode']);
    set_param([model_name, '/ControlMode'], 'Value', '1', 'Position', [60, 60, 140, 100]); % 1: MPC, 2: Stanley, 3: Pure Pursuit

    % Add MATLAB Function Block: Meghana_Controller
    ctrl_block = [model_name, '/Meghana_Control_Executive'];
    add_block('simulink/User-Defined Functions/MATLAB Function', ctrl_block);
    set_param(ctrl_block, 'Position', [250, 100, 480, 240]);

    % Populate MATLAB Function Code
    ctrl_rt = sfroot;
    m = ctrl_rt.find('-isa', 'Stateflow.Machine', 'Name', model_name);
    c = m.find('-isa', 'Stateflow.EMChart');
    if ~isempty(c)
        c(1).Script = sprintf([...
            'function [steering, throttle, brake, ey, epsi, ev, feas_code] = Meghana_Control_Executive(t, ego_x, ego_y, ego_yaw, ego_v, mode_sel)\n' ...
            '%% Master Controller Executive for SIH 26037\n' ...
            'persistent vp cp traj internal_state safetyStatus;\n' ...
            'if isempty(vp)\n' ...
            '    vp = vehicle_params();\n' ...
            '    cp = controller_params();\n' ...
            '    sc = generate_scenarios();\n' ...
            '    traj = sc.pothole_dodge;\n' ...
            '    internal_state = [];\n' ...
            '    safetyStatus = struct(''safe'',''safe'',''TTC'',99.0,''clearance'',50.0,''reason'',''OK'',''emergency_flag'',false);\n' ...
            'end\n' ...
            'modes = {''mpc'', ''stanley'', ''pure_pursuit''};\n' ...
            'm_idx = max(1, min(3, round(mode_sel)));\n' ...
            'ctrl_mode = modes{m_idx};\n' ...
            'egoState = struct(''timestamp'', t, ''pose'', [ego_x, ego_y, 0.0], ''velocity'', [ego_v, 0.0, 0.0], ''heading'', ego_yaw, ''covariance'', eye(3));\n' ...
            '[cmd, fb, internal_state] = vehicle_control_executive(traj, egoState, safetyStatus, ctrl_mode, internal_state, vp, cp);\n' ...
            'steering = cmd.steering;\n' ...
            'throttle = cmd.throttle;\n' ...
            'brake = cmd.brake;\n' ...
            'ey = fb.cross_track_err;\n' ...
            'epsi = fb.heading_err;\n' ...
            'ev = fb.speed_err;\n' ...
            'feas_code = double(fb.feasibility_code);\n' ...
            'end\n']);
    end

    % Add Scope for Output Signals
    add_block('simulink/Sinks/Scope', [model_name, '/Actuator_Commands']);
    set_param([model_name, '/Actuator_Commands'], 'Position', [580, 80, 640, 140]);

    add_block('simulink/Sinks/Scope', [model_name, '/Tracking_Errors']);
    set_param([model_name, '/Tracking_Errors'], 'Position', [580, 180, 640, 240]);

    % Add Clock for simulation time
    add_block('simulink/Sources/Clock', [model_name, '/Clock']);
    set_param([model_name, '/Clock'], 'Position', [60, 120, 120, 150]);

    % Save system
    save_system(model_name, slx_file);
    fprintf('Successfully built and saved Simulink model: %s\n', slx_file);
end
